# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
- job: job1
  steps:
  - script: echo Hello, world! changed
    displayName: 'Run a one-line script'

  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
    displayName: 'Run a multi-line script'

- job: job2
  dependsOn: job1
  condition: succeeded('job1')
  steps:
  - script: echo Hello from job2
    displayName: 'Run a one-line script in job2'

  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
    displayName: 'Run a multi-line script in job2'
- job: job3
  dependsOn: 
   - job2
   - job1
  condition: succeeded('job2')
  steps:
  - script: echo Hello from job3
    displayName: 'Run a one-line script in job3'

  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
    displayName: 'Run a multi-line script in job3'