# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs: 
  - job: FirstJob
    steps: 
    - bash: echo Hello, world! changed
      displayName: 'Run a one-line script'
  - job: SecondJob
    dependsOn: FirstJob
    condition: succeeded('FirstJob')
    steps:
    - bash: echo Hello from job2
      displayName: 'Run a one-line script in job2'
- stage : Devdeploy
  dependsOn: Build
  jobs:
  - job: DevdeployJob
    steps:
    - bash: echo Hello from DevdeployJob
      displayName: 'Run a one-line script in DevdeployJob'
  - job: DevdeployJob2
    dependsOn: DevdeployJob
    condition: succeeded('DevdeployJob')
    steps:
    - bash: echo Hello from DevdeployJob2
      displayName: 'Run a one-line script in DevdeployJob2'